// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeFbeL6LP9j5cBdHUyqZfvQjyQGcSi3IE',
    appId: '1:911719345612:web:2c65abf91cfd2a716f4169',
    messagingSenderId: '911719345612',
    projectId: 'doaconecta',
    authDomain: 'doaconecta.firebaseapp.com',
    storageBucket: 'doaconecta.appspot.com',
    measurementId: 'G-3Y7HNXV13D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDus10nclKHXBICGHMNuNe_Xr76nvMLwl4',
    appId: '1:911719345612:android:19e7de2c2c3d3fc86f4169',
    messagingSenderId: '911719345612',
    projectId: 'doaconecta',
    storageBucket: 'doaconecta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3FkW5KUywFS0NA0yONtY1yprZCM5aW7I',
    appId: '1:911719345612:ios:f8c9c5728f93dc5f6f4169',
    messagingSenderId: '911719345612',
    projectId: 'doaconecta',
    storageBucket: 'doaconecta.appspot.com',
    iosBundleId: 'com.example.doaConectaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3FkW5KUywFS0NA0yONtY1yprZCM5aW7I',
    appId: '1:911719345612:ios:3b5e817182a7f3926f4169',
    messagingSenderId: '911719345612',
    projectId: 'doaconecta',
    storageBucket: 'doaconecta.appspot.com',
    iosBundleId: 'com.example.doaConectaApp.RunnerTests',
  );
}
